import { Search, ShoppingCart, Heart, Menu, Truck, ShieldCheck, MessageCircle, ChevronRight, MapPin, UserRound, Home, Grid2X2, Sparkles } from 'lucide-react';

const categories = ['Termos y mates','Bazar','Hogar','Belleza','Regalos','Organización'];
const products = [
  {name:'Termo premium 1 L', category:'Termos y mates', price:'₲ 189.000', old:'₲ 229.000', tag:'-17%'},
  {name:'Vaso térmico con asa', category:'Termos y mates', price:'₲ 99.000', old:'₲ 119.000', tag:'OFERTA'},
  {name:'Set matero completo', category:'Regalos', price:'₲ 149.000', old:'₲ 179.000', tag:'-16%'},
  {name:'Organizador multiuso', category:'Hogar', price:'₲ 79.000', old:'', tag:'NUEVO'},
  {name:'Botella térmica 750 ml', category:'Termos y mates', price:'₲ 129.000', old:'₲ 149.000', tag:'-13%'},
];
function ProductCard({p,i}:{p:typeof products[number],i:number}){return <article className="product-card"><div className={`product-photo photo-${i+1}`}><span className="discount">{p.tag}</span><button className="heart" aria-label="Favorito"><Heart size={18}/></button><div className="mock-product"><div className="mock-lid"/><div className="mock-body"/></div></div><div className="product-info"><small>{p.category}</small><h3>{p.name}</h3><div className="price-row"><strong>{p.price}</strong>{p.old&&<del>{p.old}</del>}</div><span className="delivery">Delivery disponible</span><button className="add">Agregar <ShoppingCart size={17}/></button></div></article>}
export default function HomePage(){return <main>
<div className="topbar"><span>Envíos a todo Paraguay</span><span className="desktop-only">Atención personalizada por WhatsApp</span><span>Compra fácil y segura</span></div>
<header className="header"><div className="head-main"><button className="menu-mobile" aria-label="Menú"><Menu/></button><a className="brand" href="#"><span>Haunted</span><small>TIENDA ONLINE</small></a><div className="search"><Search size={20}/><input aria-label="Buscar productos" placeholder="¿Qué estás buscando?"/><button>Buscar</button></div><div className="actions"><button><UserRound/><span>Mi cuenta</span></button><button><Heart/><span>Favoritos</span></button><button className="cart"><ShoppingCart/><b>0</b><span>Carrito</span></button></div></div><div className="mobile-search search"><Search size={19}/><input aria-label="Buscar productos" placeholder="Buscar en Haunted"/></div><nav><button><Menu size={18}/> Todas las categorías</button>{categories.map(c=><a key={c} href="#categorias">{c}</a>)}<a className="sale" href="#ofertas">Ofertas</a></nav></header>
<section className="hero shell"><div className="hero-copy"><span className="eyebrow">HAUNTED · TIENDA ONLINE</span><h1>Todo lo que te gusta,<br/><em>en un solo lugar.</em></h1><p>Termos, bazar, hogar, regalos y esos productos que querés tener.</p><div className="hero-actions"><a href="#ofertas">Ver ofertas <ChevronRight size={18}/></a><a className="secondary" href="#categorias">Explorar tienda</a></div><div className="hero-note"><Truck size={19}/><span>Delivery y envíos al interior</span></div></div><div className="hero-art"><div className="circle circle-a"/><div className="circle circle-b"/><div className="thermo t1"><i/><b/></div><div className="thermo t2"><i/><b/></div><span className="hero-badge"><b>OFERTAS</b><small>todos los días</small></span></div></section>
<section className="benefits shell"><div><Truck/><span><b>Envíos a todo el país</b><small>Asunción e interior</small></span></div><div><MessageCircle/><span><b>Comprá por WhatsApp</b><small>Atención personalizada</small></span></div><div><ShieldCheck/><span><b>Compra segura</b><small>Estamos para ayudarte</small></span></div><div><MapPin/><span><b>Delivery disponible</b><small>Consultá cobertura</small></span></div></section>
<section id="categorias" className="section shell"><div className="section-title"><div><span>ENCONTRÁ MÁS RÁPIDO</span><h2>Comprá por categoría</h2></div><a href="#">Ver todas <ChevronRight size={17}/></a></div><div className="category-grid">{categories.map((c,i)=><a className={`category cat-${i+1}`} key={c} href="#"><div><Grid2X2 size={28}/></div><strong>{c}</strong><small>Ver productos</small></a>)}</div></section>
<section id="ofertas" className="section shell"><div className="section-title"><div><span>PRECIOS QUE CONVIENEN</span><h2>Ofertas destacadas</h2></div><a href="#">Ver todas <ChevronRight size={17}/></a></div><div className="product-grid">{products.map((p,i)=><ProductCard key={p.name} p={p} i={i}/>)}</div></section>
<section className="promo shell"><div><span>PARA TODOS LOS DÍAS</span><h2>Tu próximo favorito<br/>está en Haunted.</h2><p>Descubrí novedades para vos, tu casa o para regalar.</p><a href="#">Descubrir novedades <ChevronRight size={18}/></a></div><div className="promo-shapes"><div/><div/><div/></div></section>
<section className="section shell"><div className="section-title"><div><span>LOS FAVORITOS DE LA TIENDA</span><h2>Más vendidos</h2></div><a href="#">Ver todos <ChevronRight size={17}/></a></div><div className="product-grid">{[...products].reverse().map((p,i)=><ProductCard key={p.name} p={p} i={(i+2)%5}/>)}</div></section>
<section className="newsletter"><div className="shell newsletter-inner"><div><Sparkles/><span><b>Enterate primero de nuestras novedades</b><small>Promos, nuevos ingresos y oportunidades.</small></span></div><div><input placeholder="Tu correo electrónico"/><button>Quiero recibir novedades</button></div></div></section>
<footer><div className="shell footer-grid"><div className="footer-brand"><span>Haunted</span><small>TIENDA ONLINE</small><p>Productos que te gustan, atención cercana y envíos a todo Paraguay.</p></div><div><b>Tienda</b><a href="#">Productos</a><a href="#">Categorías</a><a href="#">Ofertas</a><a href="#">Novedades</a></div><div><b>Ayuda</b><a href="#">Cómo comprar</a><a href="#">Envíos</a><a href="#">Cambios</a><a href="#">Contacto</a></div><div><b>Estamos para ayudarte</b><p>Escribinos y te ayudamos con tu compra.</p><button className="wa"><MessageCircle size={18}/> Hablar por WhatsApp</button></div></div><div className="copyright shell">© 2026 Haunted Tienda Online <span>Desarrollado por eQuantum</span></div></footer>
<nav className="bottom-nav"><a href="#"><Home/><span>Inicio</span></a><a href="#categorias"><Grid2X2/><span>Categorías</span></a><a href="#" className="search-bottom"><Search/><span>Buscar</span></a><a href="#"><Heart/><span>Favoritos</span></a><a href="#"><ShoppingCart/><span>Carrito</span></a></nav>
</main>}