import { Search, ShoppingCart, Heart, Menu, Truck, ShieldCheck, MessageCircle, ChevronRight, MapPin, UserRound, Home, Grid2X2, Sparkles, Flame, Clock3, Gift, ArrowRight } from 'lucide-react';

const categories = ['Termos y mates','Bazar','Hogar','Belleza','Regalos','Organización','Cocina','Accesorios'];
const products = [
{name:'Set X12 Utensilios de Cocina Mango Madera Punta Silicona',category:'Cocina',price:'₲ 115.000',old:'₲ 139.000',tag:'OFERTA',image:'/products/termo-green.svg'},
{name:'Termo Stanley Original Mate System Classic 1.2 L',category:'Termos y mates',price:'₲ 189.000',old:'₲ 219.000',tag:'-14%',image:'/products/termo-black.svg'},
{name:'Termo Stanley Mate System Rose Quartz 800 ml',category:'Termos y mates',price:'₲ 153.000',old:'₲ 179.000',tag:'OFERTA',image:'/products/termo-rose.svg'},
{name:'Stanley Classic Mate System 1.2 Lts Verde',category:'Termos y mates',price:'₲ 182.000',old:'₲ 209.000',tag:'-13%',image:'/products/termo-green.svg'},
{name:'Stanley Termo Adventure 500 ml Polar',category:'Termos y mates',price:'₲ 95.000',old:'₲ 110.000',tag:'-14%',image:'/products/termo-polar.svg'},
{name:'Botella Térmica Stanley Flip Straw 887 ml',category:'Termos y mates',price:'₲ 124.000',old:'₲ 145.000',tag:'NUEVO',image:'/products/tumbler-sage.svg'},
{name:'Botellón Stanley Iceflow Flip Straw 1.9 Lts',category:'Termos y mates',price:'₲ 214.000',old:'',tag:'NUEVO',image:'/products/tumbler-cream.svg'},
{name:'Termo Stanley Classic Negro 591 ml',category:'Termos y mates',price:'₲ 113.260',old:'',tag:'OFERTA',image:'/products/termo-black.svg'},
{name:'Botella de Agua Stanley Iceflow Fast Flow',category:'Termos y mates',price:'₲ 104.500',old:'₲ 110.000',tag:'-5%',image:'/products/tumbler-navy.svg'},
{name:'Stanley Quencher 40 Oz Vaso Acero Inoxidable',category:'Termos y mates',price:'₲ 157.000',old:'',tag:'NUEVO',image:'/products/tumbler-black.svg'},
{name:'Combo Maquillaje Tejar X10 Kit Make Up Box Completo',category:'Belleza',price:'₲ 129.000',old:'₲ 149.000',tag:'OFERTA',image:'/products/kit-maquillaje.svg'},
{name:'Máscara de Pestañas Maybelline Colossal Bubble',category:'Belleza',price:'₲ 89.000',old:'',tag:'NUEVO',image:'/products/mascara-pestanas.svg'},
{name:'Brillo Labial Maybelline Lifter Gloss',category:'Belleza',price:'₲ 79.000',old:'',tag:'NUEVO',image:'/products/lifter-gloss.svg'},
{name:'Tinta de Labios Maybelline Super Stay Teddy Tint',category:'Belleza',price:'₲ 92.000',old:'',tag:'NUEVO',image:'/products/teddy-tint.svg'},
{name:'Bronzer 3 en 1 Rimmel London Multitasker',category:'Belleza',price:'₲ 85.000',old:'',tag:'NUEVO',image:'/products/bronzer.svg'},
{name:'Paleta de Sombras Precious Obsidian Ruby Rose',category:'Belleza',price:'₲ 69.000',old:'',tag:'OFERTA',image:'/products/paleta-sombras.svg'},
{name:'Ramo de Maquillaje Profesional Mediano Tejar',category:'Regalos',price:'₲ 32.713',old:'₲ 35.500',tag:'-7%',image:'/products/ramo-maquillaje.svg'},
{name:'Ramo de Maquillaje Profesional Regalo Tejar',category:'Regalos',price:'₲ 42.659',old:'',tag:'REGALO',image:'/products/ramo-maquillaje.svg'}
];

function ProductCard({p,i}:{p:typeof products[number],i:number}){return <article className="product-card"><div className={`product-photo photo-${(i%6)+1}`}><span className="discount">{p.tag}</span><button className="heart" aria-label="Agregar a favoritos"><Heart size={18}/></button><img className="product-img" src={p.image} alt={p.name}/></div><div className="product-info"><small>{p.category}</small><h3>{p.name}</h3><div className="price-row"><strong>{p.price}</strong>{p.old&&<del>{p.old}</del>}</div><span className="delivery">Delivery disponible</span><button className="add">Agregar al carrito <ShoppingCart size={16}/></button></div></article>}
function ProductRow({items}:{items:typeof products}){return <div className="product-scroll">{items.map((p,i)=><ProductCard key={`${p.name}-${i}`} p={p} i={i}/>)}</div>}

export default function HomePage(){const ofertas=products.slice(0,6),termos=products.slice(5,11),belleza=products.slice(11,18);return <main>
<div className="topbar"><span><Truck size={13}/> Envíos a todo Paraguay</span><span className="desktop-only"><MessageCircle size={13}/> Atención por WhatsApp</span><span><ShieldCheck size={13}/> Compra fácil y segura</span></div>
<header className="header"><div className="head-main"><button className="menu-mobile" aria-label="Menú"><Menu/></button><a className="brand" href="#"><span>Haunted</span><small>TIENDA ONLINE</small></a><div className="search"><Search size={20}/><input aria-label="Buscar productos" placeholder="Buscar termos, bazar, maquillaje y más..."/><button>Buscar</button></div><div className="actions"><button><UserRound/><span>Mi cuenta</span></button><button><Heart/><span>Favoritos</span></button><button className="cart"><ShoppingCart/><b>0</b><span>Carrito</span></button></div></div><div className="mobile-search search"><Search size={19}/><input aria-label="Buscar productos" placeholder="¿Qué estás buscando?"/></div><nav><button><Menu size={18}/> Todas las categorías</button>{categories.slice(0,6).map(c=><a key={c} href="#categorias">{c}</a>)}<a className="sale" href="#ofertas">Ofertas</a></nav></header>
<section className="hero shell"><div className="hero-copy"><span className="eyebrow">HAUNTED · TIENDA ONLINE</span><h1>Todo lo que te gusta,<br/><em>en un solo lugar.</em></h1><p>Termos, bazar, belleza, regalos y productos para todos los días. Comprá fácil y recibí donde estés.</p><div className="hero-actions"><a href="#ofertas">Comprar ahora <ArrowRight size={17}/></a><a className="secondary" href="#categorias">Ver categorías</a></div></div><div className="hero-commerce"><span className="big-offer">OFERTAS<br/><b>DESTACADAS</b></span><div className="visual-card vc1">TERMOS<br/>STANLEY</div><div className="visual-card vc2">BELLEZA<br/>& REGALOS</div><div className="visual-card vc3">HOGAR<br/>& BAZAR</div></div></section>
<section className="quick shell"><a href="#ofertas"><Flame/><span><b>Ofertas</b><small>Precios especiales</small></span></a><a href="#termos"><Clock3/><span><b>Termos Stanley</b><small>Modelos disponibles</small></span></a><a href="#belleza"><Gift/><span><b>Belleza y regalos</b><small>Ideas para regalar</small></span></a><a href="#categorias"><Grid2X2/><span><b>Todas las categorías</b><small>Explorá la tienda</small></span></a></section>
<section id="categorias" className="section shell"><div className="section-title"><div><span>ENCONTRÁ MÁS RÁPIDO</span><h2>Comprá por categoría</h2></div><a href="#">Ver todas <ChevronRight size={17}/></a></div><div className="category-grid">{categories.map((c,i)=><a className={`category cat-${(i%6)+1}`} key={c} href="#"><div><Grid2X2 size={25}/></div><strong>{c}</strong><small>Explorar</small></a>)}</div></section>
<section id="ofertas" className="section shell retail-section"><div className="section-title"><div><span>APROVECHÁ HOY</span><h2>Ofertas destacadas</h2></div><a href="#">Ver todas <ChevronRight size={17}/></a></div><ProductRow items={ofertas}/></section>
<section className="commercial-grid shell"><a className="commercial commercial-dark" href="#termos"><span>ESPECIAL HAUNTED</span><h2>Termos para<br/>todos los días</h2><b>Ver colección <ChevronRight size={16}/></b></a><a className="commercial commercial-light" href="#belleza"><span>BELLEZA & REGALOS</span><h2>Detalles que<br/>te van a encantar</h2><b>Descubrir <ChevronRight size={16}/></b></a></section>
<section id="termos" className="section shell retail-section"><div className="section-title"><div><span>TERMOS Y BOTELLAS</span><h2>Stanley destacados</h2></div><a href="#">Ver todos <ChevronRight size={17}/></a></div><ProductRow items={termos}/></section>
<section className="deal shell"><div><span>OPORTUNIDAD DE LA SEMANA</span><h2>Precios que vale la pena mirar.</h2><p>Productos seleccionados con precios especiales y delivery disponible.</p></div><a href="#ofertas">Ver oportunidades <ArrowRight size={18}/></a></section>
<section id="belleza" className="section shell retail-section"><div className="section-title"><div><span>BELLEZA Y REGALOS</span><h2>Maquillaje y favoritos</h2></div><a href="#">Ver todos <ChevronRight size={17}/></a></div><ProductRow items={belleza}/></section>
<section className="benefits shell"><div><Truck/><span><b>Envíos a todo el país</b><small>Asunción e interior</small></span></div><div><MessageCircle/><span><b>Comprá por WhatsApp</b><small>Atención personalizada</small></span></div><div><ShieldCheck/><span><b>Compra segura</b><small>Estamos para ayudarte</small></span></div><div><MapPin/><span><b>Delivery disponible</b><small>Consultá cobertura</small></span></div></section>
<section className="newsletter"><div className="shell newsletter-inner"><div><Sparkles/><span><b>Promos y novedades de Haunted</b><small>Enterate primero de nuevos ingresos y oportunidades.</small></span></div><div><input placeholder="Tu correo electrónico"/><button>Quiero recibir novedades</button></div></div></section>
<footer><div className="shell footer-grid"><div className="footer-brand"><span>Haunted</span><small>TIENDA ONLINE</small><p>Productos que te gustan, atención cercana y envíos a todo Paraguay.</p></div><div><b>Tienda</b><a href="#">Productos</a><a href="#">Categorías</a><a href="#">Ofertas</a><a href="#">Novedades</a></div><div><b>Ayuda</b><a href="#">Cómo comprar</a><a href="#">Envíos</a><a href="#">Cambios</a><a href="#">Contacto</a></div><div><b>Estamos para ayudarte</b><p>Escribinos y te ayudamos con tu compra.</p><button className="wa"><MessageCircle size={18}/> Hablar por WhatsApp</button></div></div><div className="copyright shell">© 2026 Haunted Tienda Online <span>Desarrollado por eQuantum</span></div></footer>
<nav className="bottom-nav"><a href="#"><Home/><span>Inicio</span></a><a href="#categorias"><Grid2X2/><span>Categorías</span></a><a href="#" className="search-bottom"><Search/><span>Buscar</span></a><a href="#"><Heart/><span>Favoritos</span></a><a href="#"><ShoppingCart/><span>Carrito</span></a></nav>
</main>}
